<a href="https://colab.research.google.com/github/Krish-Bali/Machine-learning/blob/main/T_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Evaluating T-test


In [1]:
import numpy as np
import pandas as pd

In [2]:
ages=np.random.randint(1,80,20)

In [3]:
ages

array([23, 31, 28, 17, 50, 72, 14, 39, 74, 46, 37, 52, 79, 36, 52, 70, 60,
       63,  1, 71])

In [4]:
ages_mean=ages.mean()

In [5]:
ages_mean

45.75

In [6]:
##lets take a sample
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [7]:
age_sample

array([60, 17, 52, 50, 31, 17, 36, 70, 31, 74])

In [8]:
from scipy.stats import ttest_1samp

In [9]:
ttest,p_value=ttest_1samp(age_sample,37) #we are checking btw age_sample wheather it depnds on my mean value 37.55

In [10]:
print(p_value)

0.32211580993773475


In [11]:
if p_value <0.05:
  print("we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

we are accepting null hypothesis


**2nd Example**
consider the heieght of students in a college and in class A


In [12]:
import math
import scipy.stats as stats

In [13]:
np.random.seed(6)
school_height=stats.poisson.rvs(loc=18,mu=35,size=1500)
class_height=stats.poisson.rvs(loc=18,mu=30,size=60)

In [14]:
class_height.mean(),school_height.mean()

(46.9, 53.303333333333335)

In [15]:
_,p_values=stats.ttest_1samp(class_height,school_height.mean())

In [16]:
print(p_value)

0.32211580993773475


In [17]:
if p_value <0.05:
  print("we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

we are accepting null hypothesis


**2 Sample T test**

In [19]:
np.random.seed(0)
classB_height=stats.poisson.rvs(loc=18,mu=33,size=60)

In [24]:
ttest,p_value=stats.ttest_ind(class_height,classB_height,equal_var=False)

In [25]:
print({ttest,p_value})

{-4.746170272546785, 5.871245957557427e-06}


In [26]:
if p_value <0.05:
  print("we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

we are rejecting null hypothesis


**Paied T test**

In [31]:
weight1=np.random.randint(1,50,15)

In [32]:
weight2 = weight1 + stats.norm.rvs(scale=5,loc=1.25,size=15)

In [34]:
print(weight1,weight2)

[ 6 24 44 33 12 41 21 11 44 38 29 48 41  3 28] [ 2.57234772 26.68693826 47.05213634 36.2907406   3.54642162 49.47417855
 23.21430432 10.1456759  53.9512673  37.42956612 36.9697721  45.15889519
 42.66354968 -2.20529228 25.94447884]


In [36]:
weight_df=pd.DataFrame({"weight1":np.array(weight1),"weight2":np.array(weight2),"difference":np.array(weight1)-np.array(weight2)})

In [37]:
weight_df

weight1    weight2  difference
0         6   2.572348    3.427652
1        24  26.686938   -2.686938
2        44  47.052136   -3.052136
3        33  36.290741   -3.290741
4        12   3.546422    8.453578
5        41  49.474179   -8.474179
6        21  23.214304   -2.214304
7        11  10.145676    0.854324
8        44  53.951267   -9.951267
9        38  37.429566    0.570434
10       29  36.969772   -7.969772
11       48  45.158895    2.841105
12       41  42.663550   -1.663550
13        3  -2.205292    5.205292
14       28  25.944479    2.055521

In [38]:
_,p_value=stats.ttest_rel(weight1,weight2)

In [39]:
if p_value <0.05:
  print("we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

we are accepting null hypothesis
